version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - 8000:80

  backend:
    build: ./backend
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: olezhuravlev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
