apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: default
  labels:
    app: pv-example
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
