---
all:
  hosts:
    vm-01:
      ansible_host: "{{ vm01_ip }}"
    vm-02:
      ansible_host: "{{ vm02_ip }}"
    vm-03:
      ansible_host: "{{ vm03_ip }}"
  children:
    redis_cluster_nodes:
      hosts:
        vm-01:
        vm-02:
        vm-03:
  vars:
    ansible_connection_type: ssh
    ansible_user: ubuntu
