---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-1gb
  # namespace: default # Doesn't make sense?
  labels:
    app: web-news
    component: dbase
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ include "ns" . }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /persistentVolume1gb
  persistentVolumeReclaimPolicy: Retain
