apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: olezhuravlev/hello-world:1.0.0
        ports:
          - containerPort: 80
            name: http-web-app
            protocol: TCP

---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: hw-node-port
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - name: node-port
      protocol: TCP
      nodePort: 30000 # Visible outside cluster.
      port: 30001 # Visible within cluster.
      targetPort: http-web-app
