---
all:
  hosts:
    cp1:
      ansible_host: "{{ public_ip['cp1'] }}"
  children:
    k8n_cluster:
      hosts:
        cp1:
    k8n_control_plane:
      hosts:
        cp1:
  vars:
    ansible_connection_type: ssh
    ansible_user: "{{ ansible_user }}"
