apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-50mi
  namespace: default
  labels:
    app: alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: storage-alert-alertmanager-0
    namespace: default
  hostPath:
    path: /persistentVolume50mi
    type: ""
  storageClassName: standard
  volumeMode: Filesystem
