apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-with-error
  name: pod-with-error
  namespace: default
spec:
  containers:
  - image: nginx:1.20
    imagePullPolicy: IfNotPresent
    name: nginx
  - image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    name: multitool

