apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-wo-errors
  name: pod-wo-errors
  namespace: default
spec:
  containers:
  - image: nginx:1.20
    imagePullPolicy: IfNotPresent
    name: nginx
  - image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    name: multitool
    env:
      - name: HTTP_PORT
        value: "8080"
